### ISSUE TITLE
Add a Domain

### ISSUE THREAD

**Issue by notenociz** [mhslinks/mhslinks.github.io#3]
I, as a student, find it very time-consuming to have to type in the full domain as present. I recommend that a domain be put in place via CNAME. I wrote [a little guide](http://enociz.me/writing/publish-for-free) once to do so. I'm sure my method can be modified for use in Jekyll.

**Comment by mcpower** [comment]
(I am the founder of MHS Links, and this does not reflect the opinions on the two IT captains of this year, @peter-drew and @leaen.)

The main problems with having a custom domain is that:
- if it's a free domain, it's naturally suspicious. Firstly, they are non-standard – not many people have heard of them, and secondly other websites with free TLDs have been used for phishing/malware/etc. (especially .tk). The other TLDs mentioned in your website are much better, but I still am unsure of whether it is a good idea of not.
- if it's a paid domain, the cost of maintaining it is not worth it.

This is why I have never tried to find a custom domain for MHS Links. In the past, MHS Links used to be run on mhslinks.tumblr.com and then mc.powered.technology/mhs/ and mcpower.github.io/mhslinks/. Not many people had qualms with the domain (except that during a period of time, Tumblr was blocked by the school).

Most students' use case of "accessing MHS Links regularly"  is solved by creating a bookmark to the website. MHS Links also supports iOS webclips, acting as a native app on the home screen. If students do use MHS Links regularly, they would most likely do this or rely on browser autocompletion.

I do not currently maintain MHS Links after graduating, so the decision of whether to have a custom domain is up to @peter-drew and @leaen. (If they do agree, I'll get the current domain to redirect to the new one.)

**Comment by peter-drew** [comment]
Discussed this with @leaen today, share the view of @mcpower, and will not currently be migrating to a different domain. Current domain has a strong search engine rating.

**Comment by notenociz** [comment]
Just wanted to revisit this and say that I now agree with your feelings on the topic. Though the domain change [can be handled well](http://savvypanda.com/blog/intermediate-level/how-to-change-domain-names-not-lose-seo.html), the actual domain itself is not worth it, yet.
