### ISSUE TITLE
Photography Request Form is cut off on mobile screens

### ISSUE THREAD

**Issue by mcpower** [mhslinks/mhslinks.github.io#4]
Perhaps shorten link name to "Photo Request Form".

**Comment by notenociz** [comment]
DOCUMENTATION OF ISSUE:

On iPhone 4:
![On iPhone 4 according to responsive test.com](https://cloud.githubusercontent.com/assets/11745906/13096709/5b09d288-d56f-11e5-89f6-90ff0a44592c.jpeg)

On iPad Air (Chrome):
![Chrome iPad Air](https://cloud.githubusercontent.com/assets/11745906/13096753/aa558526-d56f-11e5-86c7-11190526a294.jpeg)

SOLUTIONS:
- continue on new line
- change text

**Comment by peter-drew** [comment]
Will fix this by changing text to 'Request Photography'.
